---
- name: Spacelift Ansible end-to-end test
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Simulate 5000 test resource creations
      debug:
        msg: "Simulated creation of testresource{{ item }}"
      loop: "{{ range(1, 8000) | list }}"
      no_log: true
